project_id = "yqvznnqcxvogxhramyua"

[functions.notify-certificate-order]
verify_jwt = false

[functions.notify-new-lead]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.chat-ai]
verify_jwt = false
